" Written by Eric Tan
"
" Vim configuration

" set the runtime path to include Vundle and initialize
filetype off
set rtp+=~/.vim/bundle/Vundle.vim

" Enable highlighting and syntax
filetype indent plugin on
syntax on

" Basics
set background=dark
set number
set wildmenu
set noerrorbells
set scrolloff=5
set noerrorbells

" Vim compatability
set nocompatible
set noexrc

" Ignore certian files
set wildignore=*.dll,*.exe,*.o,*.obj,*.out,*.jpg,*.gif,*.png,*.pdf

" Those who enable auto match brackets are assholes
set noshowmatch

" Search options
set hlsearch
set ignorecase
set smartcase
set incsearch

" Set tabbing
set shiftwidth=4
set softtabstop=4
set ts=4
set expandtab
set smarttab
set cindent
set autoindent
set smartindent

" Set commandline
set laststatus=2
set cmdheight=2
set showcmd

" Stop autocomments
set formatoptions-=cro

" Set alternative tabbing for Makefiles
au BufRead,BufNewfile Makefile set ts=4 sw=4 noexpandtab

" Highlight trailing whitespaces
match ErrorMsg /\s\+\%$\@<!$/

" Highlight past 80 char
" GET MATCH 80 CHAR AND TRAILING WHITESPACE TO WORK TOGETHER LATER
"match ErrorMsg '\%>81v.\+'

" Matain indent for c preprocessor
set cinkeys=0{,0},0),:,!^F,o,0,e

" Set backup
set backup
set backupdir=~/.vim/backup
set directory=~/.vim/swapfile

" set unix as standard file type
set ffs=unix,mac,dos

" Set utf8
set enc=utf-8
set fenc=utf-8

" Return to last editied position
augroup vimrcEx
  autocmd!
  autocmd BufReadPost *
    \ if line("'\"") > 0 && line("'\"") <= line("$") |
    \ exe "normal g`\"" |
    \ endif
augroup END

" Format status line
set statusline=\ %t\ %w\ \ CWD:\%r%{getcwd()}%h\ %=\ Line:\ %l\ \ Col:\ %c

" Arrow keys are for the weak
no <down> <Nop>
no <up> <Nop>
no <left> <Nop>
no <right> <Nop>
ino <down> <Nop>
ino <up> <Nop>
ino <left> <Nop>
ino <right> <Nop>
vno <down> <Nop>
vno <up> <Nop>
vno <left> <Nop>
vno <right> <Nop>

" Plugins with vundle
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
call vundle#end()
