" Written by Eric Tan
"
" Vim configuration
    
" set the runtime path to include Vundle and initialize
filetype off
set rtp+=~/.vim/bundle/Vundle.vim

" Enable highlighting and syntax
filetype indent plugin on
syntax on

" Basics
set background=dark
set number
set wildmenu
set noerrorbells
set scrolloff=5
set noerrorbells

" Vim compatability
set nocompatible
set noexrc

" Ignore certian files
set wildignore=*.dll,*.exe,*.o,*.obj,*.out,*.jpg,*.gif,*.png,*.pdf

" Search options
set hlsearch
set ignorecase
set smartcase
set incsearch

" Set tabbing
set shiftwidth=2
set softtabstop=2
set ts=2
set expandtab
set smarttab
set cindent
set autoindent
set smartindent

" Set commandline
set laststatus=2
set cmdheight=2
set showcmd

" Stop autocomments
set formatoptions-=cro

" Set alternative tabbing for Makefiles
au BufRead,BufNewfile Makefile set ts=4 sw=4 noexpandtab

" Highlight trailing whitespaces
match ErrorMsg /\s\+\%$\@<!$/

" Highlight past 80 char
" GET MATCH 80 CHAR AND TRAILING WHITESPACE TO WORK TOGETHER LATER
"match ErrorMsg '\%>81v.\+'

" Matain indent for c preprocessor
set cinkeys=0{,0},0),:,!^F,o,0,e

" Set backup
set backup
set backupdir=~/.vim/backup
set directory=~/.vim/swapfile

" set unix as standard file type
set ffs=unix,mac,dos

" Set utf8
set enc=utf-8
set fenc=utf-8

" Return to last editied position
augroup vimrcEx
  autocmd!
  autocmd BufReadPost *
    \ if line("'\"") > 0 && line("'\"") <= line("$") |
    \ exe "normal g`\"" |
    \ endif
augroup END

" Format status line
"set statusline=\ %t\ %w\ \ CWD:\%r%{getcwd()}%h\ %=\ Line:\ %l\ \ Col:\ %c

" Arrow keys are for the weak
no <down> <Nop>
no <up> <Nop>
no <left> <Nop>
no <right> <Nop>
ino <down> <Nop>
ino <up> <Nop>
ino <left> <Nop>
ino <right> <Nop>
vno <down> <Nop>
vno <up> <Nop>
vno <left> <Nop>
vno <right> <Nop>

" Powerline configure
set ttimeoutlen=50
let g:airline_theme = 'powerlineish'
let g:airline#extensions#hunks#enabled=1
let g:airline#extensions#branch#enabled=1

" Powerline fonts
let g:airline_powerline_fonts = 1
if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif
" unicode symbols
let g:airline_left_sep = '»'
let g:airline_left_sep = '▶'
let g:airline_right_sep = '«'
let g:airline_right_sep = '◀'
let g:airline_symbols.linenr = '␊'
let g:airline_symbols.linenr = '␤'
let g:airline_symbols.linenr = '¶'
let g:airline_symbols.branch = '⎇'
let g:airline_symbols.paste = 'ρ'
let g:airline_symbols.paste = 'Þ'
let g:airline_symbols.paste = '∥'
let g:airline_symbols.whitespace = 'Ξ'
" airline symbols
let g:airline_left_sep = ''
let g:airline_left_alt_sep = ''
let g:airline_right_sep = ''
let g:airline_right_alt_sep = ''
let g:airline_symbols.branch = ''
let g:airline_symbols.readonly = ''
let g:airline_symbols.linenr = ''

" Plugins with vundle
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
call vundle#end()
